### PR TITLE
Add missing first triangle in STL parser

### PR DESCRIPTION
**Pull request by h3ndrk**
This PR fixes a small bug in the STL parser: The first triangle from the STL is not added to `coordIndex` in the current `master` branch. This PR adds it correctly.

### CODE REVIEW

**Comment by h3ndrk** [comment]
`python -m unittest discover -s tests` now produces:

```
...
Ran 2 tests in 5.901s

OK
```

**Review by lukicdarkoo — APPROVED** [review]
Perfect, thank you

**Comment by lukicdarkoo** [comment]
@h3ndrk You should be able to merge the PR

**Comment by h3ndrk** [comment]
Great, @lukicdarkoo!

I cannot merge, since "Only those with write access to this repository can merge pull requests." :wink:  
Feel free to merge, thanks! :+1:

**Comment by lukicdarkoo** [comment]
> Great, @lukicdarkoo!
> 
> I cannot merge, since "Only those with write access to this repository can merge pull requests." 
> Feel free to merge, thanks!

You should have received an invitation to the Cyberbotics organization (as a member)

**Comment by h3ndrk** [comment]
@lukicdarkoo Thank you very much!

**Pull request merged**
