### PR TITLE
Remove special rotation for cylinders

### PR DESCRIPTION
**Pull request by BenjaminHug8**
Some URDF files were not correctly converted, as some links were not rotated in the correct way. This was due to a special case for the cylinder before the conversion to FLU/ENU.

This PR remove this exception.

### CODE REVIEW

**Review by omichel — APPROVED** [review]
Well spotted!

**Comment by Timple** [comment]
Would it be possible to create a new python-pip release with this fix?

**Comment by BenjaminHug8** [comment]
> Would it be possible to create a new python-pip release with this fix?

It should be out with [1.0.14](https://github.com/cyberbotics/urdf2webots/releases/tag/1.0.14).
Do you still have issues with 1.0.14 and beyond for the cylinders?

**Comment by Timple** [comment]
Ah, missed that. Thanks!

**Pull request merged**
