### PR TITLE
Update version to R2021b

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
update to R2021b

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
Maybe we should also upgrade the headers in the `tests/expected` directory?

**Comment by BenjaminDeleze** [comment]
Good idea, it seems that the tests were already broken, I will try to fix them

**Comment by BenjaminDeleze** [comment]
It should be good now. I will fix the release info page too.

**Review by lukicdarkoo — APPROVED** [review]
Thank you

**Pull request merged**
